### ISSUE TITLE
Save widget positions

### ISSUE THREAD

**Issue by ghost** [ericlbarnes/Status-Board#15]
New to Laravel so I wasn't sure what was the best way to save the positions of the widgets.

I was thinking to write the boards config file with the updated positions but there may be a better way?

**Comment by douggrubba** [comment]
My first thought would be a cookie.

@ericbarnes Are you still trying to get away with no db?

**Comment by ericlbarnes** [comment]
I am not totally against a db and that may actually be the best route.

**Comment by ghost** [comment]
I would prefer something persistent so that when people look at the board from different sources they are all looking at the same layout.

**Comment by ericlbarnes** [comment]
I will say lets go the db route. I will take this task and should have time this coming week. Probably start with mysql but I know laravel also supports several others just like CI.

**Comment by ericlbarnes** [comment]
I pushed up a very rough first draft of db migrations. It is late and couldn't think clearly about all the tables and options but you should be able to follow along in that branch: 
https://github.com/ericbarnes/Status-Board/tree/feature/migrations

FYI migrations are ran via cli. 

```
php artisan migrate:install # to install migration table
php artisan migrate # to go to latest
php artisan migrate:rollback # go backwards
php artisan migrate:make name # To create new migration file.
```

**Comment by ghost** [comment]
http://gridster.net/ - this looks like a good tool to use for the drag and drop
