### ISSUE TITLE
Widget sizes

### ISSUE THREAD

**Issue by ghost** [ericlbarnes/Status-Board#16]
//cc @ericbarnes //cc @eric-famiglietti 

I think we should adopt some specific widget sizes with defined heights and widths rather than percentages so they can slot in more easily.

Eg the medium size has a different height to the tiny, small and large sizes.

Suggestion for sizes and possible filenames:
230x230 - 1_1
230x460 - 1_2
460x230 - 2_1
460x460 - 2_2
920x230 - 4_1
920x460 - 4_2

What do ye think?

**Comment by ericlbarnes** [comment]
Yeah I agree with this. Might have to adjust based on margins and padding but I think it needs standard heights and widths.

**Comment by douggrubba** [comment]
Just a thought on this, why not use one of css frameworks for a grid?  http://960.gs is pretty light.

**Comment by ericlbarnes** [comment]
@douggdev Yeah I thought about that. But then I was thinking a status board may be used on something huge like a tv. So 960 may not be big enough. Not saying I am not open to the idea just outlining my thoughts. I am good with it if we all agree.

**Comment by douggrubba** [comment]
Maybe something more like this then:

http://framelessgrid.com/ (https://github.com/jonikorpi/Frameless)

Goes to 2560px but is "responsive."

**Comment by ghost** [comment]
http://foundation.zurb.com/ (https://github.com/zurb/foundation) is another option.

Either one is good with me.

**Comment by douggrubba** [comment]
I don't really have a preference on either, both look pretty cool.

My vote would probably be for using one of these tools though.  Might as well build off one these frameworks instead of writing a new solution.

**Comment by eric-famiglietti** [comment]
I agree with the use of standard widget sizes but I think whichever way we go it's important that the design is responsive.  I think one of the main appeals of [Geckoboard](http://www.geckoboard.com/) is that it looks great in different devices.  I think that's a very valuable feature.

**Comment by ghost** [comment]
Agreed

**Comment by ericlbarnes** [comment]
So did we come to a conclusion here? I think everyone agrees on a grid framework so just finding the one that is the most suitable.

**Comment by ghost** [comment]
So this will be handled by Bootstrap ?

**Comment by ericlbarnes** [comment]
yep let's close this one too. :shipit:
