### ISSUE TITLE
Widget loading broken

### ISSUE THREAD

**Issue by eric-famiglietti** [ericlbarnes/Status-Board#20]
This was broken by me when I committed before updating.  I'm not sure how to roll back the repo or fix this.  Here is the relevant commit: https://github.com/ericbarnes/Status-Board/commit/324e77d47673c8e84c71e49d4fb34ac50e62c318

**Comment by ericlbarnes** [comment]
I just did a fresh pull and the widgets are loading for me?

**Comment by eric-famiglietti** [comment]
Hmm, I thought it was still broken but admittedly I did not confirm.  If it's all set then we just close this and I will update my copy tonight.
