### ISSUE TITLE
Convert theme to bootstrap

### ISSUE THREAD

**Issue by ericlbarnes** [ericlbarnes/Status-Board#22]
Need to convert the themes to bootstrap.

**Comment by ghost** [comment]
Has anyone had a chance to look at this one?

If not can you give some direction for how you would like it done any maybe we could have a start here?

**Comment by ericlbarnes** [comment]
My thoughts are to use the less files and compile it ourselves. Then use the responsive part with the fluid grid. http://twitter.github.com/bootstrap/scaffolding.html#fluidGridSystem

Finally maybe remove the sizes and just allow the creators to define how big it should be. Not totally sure if that is a good idea or not.

**Comment by ericlbarnes** [comment]
Looks useful - http://gridster.net
