### ISSUE TITLE
Wait for Laravel 3.1

### ISSUE THREAD

**Issue by douggrubba** [ericlbarnes/Status-Board#23]
Eloquent 2, the new blade features...

Seem like they are worth waiting for?

**Comment by ericlbarnes** [comment]
Yes v3.1 is due out tomorrow.  It should be a pretty sweet upgrade.

**Comment by douggrubba** [comment]
:beer:

Sweet, didn't realize.  What is taking so long!?!  Haha.

Can't wait.  Screencasts have been awesome.
