### ISSUE TITLE
Twitter Widget and Curl

### ISSUE THREAD

**Issue by ghost** [ericlbarnes/Status-Board#4]
I came across a problem this morning where the Twitter widget wouldn't return anything and after some investigation found that the Curl error was "Could not resolve host: search.twitter.com; No error 6".

The only way I could fix this was to add
`curl_setopt($ch, CURLOPT_DNS_USE_GLOBAL_CACHE, FALSE);`

Have you found this issue before or a different solution?

**Comment by ghost** [comment]
I'm able to access the search api url in the browser without problems.

**Comment by ghost** [comment]
I restarted my local apache server and it worked fine.

Odd.

**Comment by ericlbarnes** [comment]
Must be apache problem. lol :D

**Comment by ghost** [comment]
Yeah I'll close this :-)
